### GENERAL SETTINGS ###

# Site settings
title: Mission and Market
description: "Capital for founders with bold missions in big markets"
analytics: UA-31324987-7
baseurl: "" #important: start with /
url: "http://m14t.com"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: twitter
    url: http://twitter.com/missionmarketvc 
  - title: angellist
    url: http://angel.co/mission-and-market
    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - San Francisco, CA
    - United States
email: team@m14t.com
# tel: +34 8493-4893


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
members:
  - name: Francesco Simoneschi
    position: Partner
    text: "After having sold his second company Francesco is now a strategic consultant for a number of startups.   <br /> Previously, he was a Product Manager at UpSight, a mobile analytics company founded in 2007 that has raised more than $50M in venture capital. As an enterpreneur, he co-founded Staq, a startup incubated by Microsoft and TechStars in Seattle and later acquired by UpSight. <br /> In 2007, Francesco also founded DomainsBot, an Italian company which is now part of the German group Sedo Holding Gmbh. In a previous life, he was a professional tenor, with more than three hundred live performances in Europe and Asia. In his spare time he plays the violin, is a sailing enthusiast and, more recently, he has dedicated himself to surf on the coast of California."
    img: fra.jpg
    social:
      - title: envelope #use for email address
        url: mailto:francesco@m14t.com
      - title: twitter
        url: http://twitter.com/fsimoneschi
  - name: Simone Brunozzi
    position: Partner
    text: "Simone is currently CTO for Mosaixsoft Inc., a startup building cloud computing software. Previously, Simone served as a Vice President and Chief Technologist (global role) for VMware Inc., focusing on Cloud technology (vCloud Air), for two years. <br /> Before that, he spent six years at Amazon Web Services (AWS) as Technology Evangelist. In his distant past, he was a serial entrepreneur, a University professor at the young age of 26, a CTO.  <br />  <br />Simone is based in San Francisco, California."
    img: brunozzi.jpg
    social:
      - title: envelope #use for email address
        url: mailto:simone@m14t.com
      - title: twitter
        url: http://twitter.com/simon
  - name: Stefano Bernardi
    position: Partner
    text: "Stefano is an entrepreneur, operator and investor. He most recently co-founded Kickpay, a fintech startup backed by the most successful VCs in the valley and part of Y Combinator's W15 batch. <br /> Previously Stefano was the first employee at Betable, where he helped the company scale to 40 people with $30M in funding. Stefano has worked in venture capital in Italy at dPixel, shadowed Dave McClure at 500 Startups, written for TechCrunch Europe and founded Italian Startup Scene (a 22k+ FB group). <br /> <br /> In his spare time - ha just kidding, he doesn't have any spare time! But he loves to spend time with his wife and son."
    img: ste.jpg
    social:
      - title: envelope #use for email address
        url: mailto:stefano@m14t.com
      - title: twitter
        url: http://twitter.com/stefanobernardi
    
# Clients information. Shown on Home and About pages.
clients:
  - name: dribbble
    img: client01.png
  - name: Code is Poetry
    img: client02.png
  - name: Vimeo
    img: client03.png
  - name: VimeoPro
    img: client04.png
    
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Capital for founders with bold missions in big markets."

# Testimonial content. Shown on Home and About page. 
testimonial:
    message: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged."
    author: Marcel Newman
    position: WEB DESIGNER - BLACKTIE.CO